#! /bin/bash

# Month number to name
# Author : Jaseem Abid <jaseemabid@gmail.com>


case $1 in
	1  ) echo "January";;
	2  ) echo "Feb" ;;
	3  ) echo "March" ;;
	4  ) echo "April" ;;
	5  ) echo "May" ;;
	6  ) echo "June" ;;
	7  ) echo "July" ;;
	8  ) echo "August" ;;
	9  ) echo "Sept" ;;
	10 ) echo "Oct" ;;
	11 ) echo "November" ;;
	12 ) echo "December" ;;
	*  ) echo "Invalid Month"
esac
