#! /bin/bash

# Shell script to find factorial of a given number.
# Author : Jaseem Abid <jaseemabid@gmail.com>

factorial()
{
	if [ $1 -gt 1 ]; then
		i=`expr $1 - 1`
		j=$(echo "$1 * $(factorial $i)" | bc )
			echo $j
	else
		echo 1
	fi
}

# Invoke

	echo -e "\nFactorial of $1 is : \c"
	factorial $1
	echo -e "\n" && exit 0
fi

